---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jirabot
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  selector:
    matchLabels:
      app: jirabot
  template:
    metadata:
      labels:
        app: jirabot
    spec:
      containers:
      - name: jirabotd
        image: artifactory.datapwn.com/tlnd-docker-at/talend/internal-utils/talend-slack-bots/jirabot:0.0.2
        imagePullPolicy: IfNotPresent