---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jirabot
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  selector:
    matchLabels:
      app: jirabot
  template:
    metadata:
      labels:
        app: jirabot
    spec:
      containers:
      - name: jirabotd
        image: localhost:5000/tlnd-docker-dev/talend/management-console/tmc-qa/talend-slack-bots/jirabot:0.0.3
        imagePullPolicy: IfNotPresent