---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry
        imagePullPolicy: IfNotPresent
        ports:
      - name: http
          containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: demo
  labels:
    app: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - port: 5000

